config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_parameters)
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_parameters)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_parameters
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>

  <%= a.label :content %>
  <%= a.text_field :content %>

  <%= a.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>Welcome to WikiniSaus</h1>

<h3>List of articles:</h3>
<ul>
  <% @articles.each do |article| %>
  <li>
    <%= link_to "#{article.title}", article_path(article) %>
  </li>
  <% end %>
</ul>

<%= link_to "Add a new article", new_article_path %>

app/views/articles/new.html.erb
<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>

  <%= a.label :content %>
  <%= a.text_field :content %>

  <%= a.submit %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>


<%= Kramdown::Document.new(@article.content).to_html.html_safe %>

<p>
<%= link_to "Edit article ", edit_article_path(@article) %> ||
<%= link_to "Delete article ", article_path(@article), method: :delete %>
 ||
<%= link_to "Back to all articles", articles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>